// main.cpp
//
// Stand-alone stress test for the CPU implementation in cpu.cpp/cpu.h.
//
// The harness pokes opcodes directly into RAM at PC=0, sets up registers,
// calls execute() once (or in a loop for multi-instruction sequences), and
// checks results against an independent reference model computed in plain
// C++ (not reusing the CPU's own bit-serial logic), plus a randomized fuzz
// pass that cross-checks the CPU against the reference model for every
// opcode-with-operand combination it can drive.


// THIS WHOLE STRESS TEST WAS AI-GENERATED BY CLAUDE.AI
// I'M NOT NO LIFE ENOUGH TO SPEND A WHOLE DAY MAKING THIS SHIT


#include "cpu/cpu.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <random>
#include <string>
#include <vector>

// Using the real RAM class from mem.h (included via cpu.h) — it already
// exposes a public `mem[1<<16]` array and read()/write().

// ---------------------------------------------------------------------------
// Tiny test framework
// ---------------------------------------------------------------------------
static int g_pass = 0;
static int g_fail = 0;

#define CHECK(cond, msg)                                                     \
    do {                                                                     \
        if (cond) {                                                          \
            ++g_pass;                                                        \
        } else {                                                             \
            ++g_fail;                                                        \
            std::printf("  [FAIL] %s:%d  %s\n", __FILE__, __LINE__, msg);    \
        }                                                                    \
    } while (0)

#define CHECK_EQ(actual, expected, label)                                    \
    do {                                                                     \
        auto a_ = (actual);                                                  \
        auto e_ = (expected);                                                \
        if (a_ == e_) {                                                      \
            ++g_pass;                                                        \
        } else {                                                             \
            ++g_fail;                                                        \
            std::printf("  [FAIL] %s:%d  %s: got 0x%02X want 0x%02X\n",      \
                         __FILE__, __LINE__, label,                          \
                         static_cast<unsigned>(a_), static_cast<unsigned>(e_));\
        }                                                                    \
    } while (0)

static void section(const char* name) { std::printf("\n== %s ==\n", name); }

// Flag bit helpers (Z N H C in bits 7-4 of F).
static bool fZ(uint8_t f) { return (f >> 7) & 1; }
static bool fN(uint8_t f) { return (f >> 6) & 1; }
static bool fH(uint8_t f) { return (f >> 5) & 1; }
static bool fC(uint8_t f) { return (f >> 4) & 1; }
static uint8_t mkF(bool z, bool n, bool h, bool c) {
    return (z << 7) | (n << 6) | (h << 5) | (c << 4);
}

// Load a byte sequence into RAM starting at addr and point PC there.
static void load(RAM& ram, CPU& cpu, uint16_t addr, std::vector<uint8_t> bytes) {
    for (size_t i = 0; i < bytes.size(); ++i) ram.write(addr + i, bytes[i]);
    cpu.reg.PC = addr;
}

static void reset(RAM& ram, CPU& cpu) {
    std::memset(ram.mem, 0, sizeof(ram.mem));
    cpu.init();
}

// ---------------------------------------------------------------------------
// 1) ADD / ADC / SUB / SBC / AND / OR / XOR / CP  — 8-bit ALU, exhaustive
//    on interesting boundary values, plus flag checks against a reference
//    implementation using plain integer arithmetic.
// ---------------------------------------------------------------------------
static void test_add(RAM& ram, CPU& cpu) {
    section("ADD A, d8");
    struct Case { uint8_t a, r; };
    std::vector<Case> cases = {
        {0x00, 0x00}, {0x0F, 0x01}, {0xFF, 0x01}, {0x80, 0x80},
        {0x3A, 0xC6}, {0x50, 0x50}, {0x00, 0xFF}, {0xFF, 0xFF},
    };
    for (auto& c : cases) {
        reset(ram, cpu);
        cpu.reg.A = c.a;
        load(ram, cpu, 0, {0xC6, c.r}); // ADD A, d8
        cpu.execute();

        int raw = c.a + c.r;
        uint8_t expect = raw & 0xFF;
        bool z = expect == 0;
        bool h = ((c.a & 0xF) + (c.r & 0xF)) > 0xF;
        bool cflag = raw > 0xFF;

        char label[64];
        std::snprintf(label, sizeof(label), "ADD A=%02X r=%02X result", c.a, c.r);
        CHECK_EQ(cpu.reg.A, expect, label);
        CHECK(fZ(cpu.reg.F) == z, "ADD Z flag");
        CHECK(fN(cpu.reg.F) == false, "ADD N flag must be 0");
        CHECK(fH(cpu.reg.F) == h, "ADD H flag");
        CHECK(fC(cpu.reg.F) == cflag, "ADD C flag");
    }
}

static void test_adc(RAM& ram, CPU& cpu) {
    section("ADC A, d8 (with carry-in)");
    struct Case { uint8_t a, r; bool cin; };
    std::vector<Case> cases = {
        {0x0F, 0x00, true}, {0xFF, 0x00, true}, {0x3A, 0xC5, true},
        {0x00, 0x00, false}, {0xFE, 0x01, true},
    };
    for (auto& c : cases) {
        reset(ram, cpu);
        cpu.reg.A = c.a;
        cpu.reg.F = c.cin ? 0x10 : 0x00;
        load(ram, cpu, 0, {0xCE, c.r}); // ADC A, d8
        cpu.execute();

        int raw = c.a + c.r + (c.cin ? 1 : 0);
        uint8_t expect = raw & 0xFF;
        bool z = expect == 0;
        bool h = ((c.a & 0xF) + (c.r & 0xF) + (c.cin ? 1 : 0)) > 0xF;
        bool cflag = raw > 0xFF;

        CHECK_EQ(cpu.reg.A, expect, "ADC result");
        CHECK(fZ(cpu.reg.F) == z, "ADC Z flag");
        CHECK(fH(cpu.reg.F) == h, "ADC H flag");
        CHECK(fC(cpu.reg.F) == cflag, "ADC C flag");
    }
}

static void test_sub_sbc_cp(RAM& ram, CPU& cpu) {
    section("SUB / SBC / CP");
    struct Case { uint8_t a, r; };
    std::vector<Case> cases = {
        {0x00, 0x01}, {0x10, 0x01}, {0x3E, 0x0F}, {0xFF, 0xFF}, {0x00, 0x00},
    };
    for (auto& c : cases) {
        // SUB B
        reset(ram, cpu);
        cpu.reg.A = c.a; cpu.reg.B = c.r;
        load(ram, cpu, 0, {0x90}); // SUB B
        cpu.execute();
        int raw = c.a - c.r;
        uint8_t expect = raw & 0xFF;
        bool h = (c.a & 0xF) < (c.r & 0xF);
        bool cflag = c.a < c.r;
        CHECK_EQ(cpu.reg.A, expect, "SUB result");
        CHECK(fN(cpu.reg.F) == true, "SUB N flag must be 1");
        CHECK(fH(cpu.reg.F) == h, "SUB H flag");
        CHECK(fC(cpu.reg.F) == cflag, "SUB C flag");

        // CP B — same flags, but A must be UNCHANGED
        reset(ram, cpu);
        cpu.reg.A = c.a; cpu.reg.B = c.r;
        load(ram, cpu, 0, {0xB8}); // CP B
        cpu.execute();
        CHECK_EQ(cpu.reg.A, c.a, "CP must not modify A");
        CHECK(fZ(cpu.reg.F) == (expect == 0), "CP Z flag");
        CHECK(fH(cpu.reg.F) == h, "CP H flag");
        CHECK(fC(cpu.reg.F) == cflag, "CP C flag");
    }
}

static void test_logic(RAM& ram, CPU& cpu) {
    section("AND / OR / XOR");
    struct Case { uint8_t a, r; };
    std::vector<Case> cases = { {0xF0, 0x0F}, {0xFF, 0xFF}, {0x00, 0x00}, {0xAA, 0x55} };
    for (auto& c : cases) {
        reset(ram, cpu); cpu.reg.A = c.a;
        load(ram, cpu, 0, {0xE6, c.r}); cpu.execute(); // AND d8
        uint8_t e = c.a & c.r;
        CHECK_EQ(cpu.reg.A, e, "AND result");
        CHECK(fH(cpu.reg.F) == true, "AND must set H=1");
        CHECK(fC(cpu.reg.F) == false, "AND must clear C");

        reset(ram, cpu); cpu.reg.A = c.a;
        load(ram, cpu, 0, {0xF6, c.r}); cpu.execute(); // OR d8
        e = c.a | c.r;
        CHECK_EQ(cpu.reg.A, e, "OR result");
        CHECK(fH(cpu.reg.F) == false, "OR must clear H");
        CHECK(fC(cpu.reg.F) == false, "OR must clear C");

        reset(ram, cpu); cpu.reg.A = c.a;
        load(ram, cpu, 0, {0xEE, c.r}); cpu.execute(); // XOR d8
        e = c.a ^ c.r;
        CHECK_EQ(cpu.reg.A, e, "XOR result");
    }
}

// ---------------------------------------------------------------------------
// 2) INC/DEC 8-bit and 16-bit, boundary wraparound
// ---------------------------------------------------------------------------
static void test_inc_dec(RAM& ram, CPU& cpu) {
    section("INC/DEC 8-bit boundaries");
    reset(ram, cpu);
    cpu.reg.A = 0xFF; cpu.reg.F = 0x10; // carry set, must be preserved by INC/DEC
    load(ram, cpu, 0, {0x3C}); cpu.execute(); // INC A
    CHECK_EQ(cpu.reg.A, 0x00, "INC 0xFF wraps to 0x00");
    CHECK(fZ(cpu.reg.F) == true, "INC wrap sets Z");
    CHECK(fH(cpu.reg.F) == true, "INC 0xFF->0x00 sets H");
    CHECK(fC(cpu.reg.F) == true, "INC must preserve pre-existing C");

    reset(ram, cpu);
    cpu.reg.A = 0x00; cpu.reg.F = 0x00;
    load(ram, cpu, 0, {0x3D}); cpu.execute(); // DEC A
    CHECK_EQ(cpu.reg.A, 0xFF, "DEC 0x00 wraps to 0xFF");
    CHECK(fN(cpu.reg.F) == true, "DEC sets N");
    CHECK(fH(cpu.reg.F) == true, "DEC 0x00->0xFF sets H (borrow)");

    section("INC/DEC 16-bit wraparound");
    reset(ram, cpu);
    cpu.reg.sBC(0xFFFF);
    load(ram, cpu, 0, {0x03}); cpu.execute(); // INC BC
    CHECK_EQ(cpu.reg.BC(), 0x0000, "INC BC wraps 0xFFFF->0x0000");

    reset(ram, cpu);
    cpu.reg.sHL(0x0000);
    load(ram, cpu, 0, {0x2B}); cpu.execute(); // DEC HL
    CHECK_EQ(cpu.reg.HL(), 0xFFFF, "DEC HL wraps 0x0000->0xFFFF");

    // INC (HL) / DEC (HL) must touch memory, not a register
    reset(ram, cpu);
    cpu.reg.sHL(0x8000); ram.write(0x8000, 0x0F);
    load(ram, cpu, 0, {0x34}); cpu.execute(); // INC (HL)
    CHECK_EQ(ram.read(0x8000), 0x10, "INC (HL) memory result");
    CHECK(fH(cpu.reg.F) == true, "INC (HL) half-carry");
}

// ---------------------------------------------------------------------------
// 3) ADD HL, rr  — 16-bit add, half-carry at bit 11, N cleared, Z preserved
// ---------------------------------------------------------------------------
static void test_add16(RAM& ram, CPU& cpu) {
    section("ADD HL, rr");
    reset(ram, cpu);
    cpu.reg.sHL(0x0FFF); cpu.reg.sBC(0x0001);
    cpu.reg.F = 0x80; // Z set beforehand — must be preserved
    load(ram, cpu, 0, {0x09}); cpu.execute(); // ADD HL, BC
    CHECK_EQ(cpu.reg.HL(), 0x1000, "ADD HL,BC result");
    CHECK(fZ(cpu.reg.F) == true, "ADD HL,rr must preserve Z");
    CHECK(fN(cpu.reg.F) == false, "ADD HL,rr clears N");
    CHECK(fH(cpu.reg.F) == true, "ADD HL,rr half-carry at bit 11");
    CHECK(fC(cpu.reg.F) == false, "ADD HL,rr no full carry here");

    reset(ram, cpu);
    cpu.reg.sHL(0xFFFF); cpu.reg.sBC(0x0001);
    load(ram, cpu, 0, {0x09}); cpu.execute();
    CHECK_EQ(cpu.reg.HL(), 0x0000, "ADD HL,BC full wraparound");
    CHECK(fC(cpu.reg.F) == true, "ADD HL,rr sets C on 16-bit overflow");
}

// ---------------------------------------------------------------------------
// 4) ADD SP, r8 / LD HL, SP+r8 — signed 8-bit offsets, negative values
// ---------------------------------------------------------------------------
static void test_sp_relative(RAM& ram, CPU& cpu) {
    section("ADD SP, r8 (negative offset)");
    reset(ram, cpu);
    cpu.reg.SP = 0x0005;
    load(ram, cpu, 0, {0xE8, 0xFB}); // ADD SP, -5  -> SP should become 0x0000
    cpu.execute();
    CHECK_EQ(cpu.reg.SP, 0x0000, "ADD SP,-5 from 0x0005");
    CHECK(fZ(cpu.reg.F) == false, "ADD SP,r8 always clears Z");
    CHECK(fN(cpu.reg.F) == false, "ADD SP,r8 always clears N");

    section("LD HL, SP+r8 (negative offset, borrow across SP)");
    reset(ram, cpu);
    cpu.reg.SP = 0x0000;
    load(ram, cpu, 0, {0xF8, 0xFF}); // LD HL, SP + (-1) -> 0xFFFF
    cpu.execute();
    CHECK_EQ(cpu.reg.HL(), 0xFFFF, "LD HL,SP-1 from SP=0");
}

// ---------------------------------------------------------------------------
// 5) Rotates + DAA edge cases (including the classic BCD-after-subtraction
//    case, since the code carries a comment about a 1h37m bug near here)
// ---------------------------------------------------------------------------
static void test_rotates(RAM& ram, CPU& cpu) {
    section("RLCA/RLA/RRCA/RRA");
    reset(ram, cpu);
    cpu.reg.A = 0x85; cpu.reg.F = 0xF0; // all flags set beforehand
    load(ram, cpu, 0, {0x07}); cpu.execute(); // RLCA
    CHECK_EQ(cpu.reg.A, 0x0B, "RLCA rotates bit7 into bit0 and C");
    CHECK(fZ(cpu.reg.F) == false, "RLCA always clears Z");
    CHECK(fC(cpu.reg.F) == true, "RLCA carry out = old bit7");

    reset(ram, cpu);
    cpu.reg.A = 0x01; cpu.reg.F = 0x00; // C=0
    load(ram, cpu, 0, {0x17}); cpu.execute(); // RLA
    CHECK_EQ(cpu.reg.A, 0x02, "RLA shifts in old C (0)");
    CHECK(fC(cpu.reg.F) == false, "RLA carry out = old bit7 (0)");
}

static void test_daa(RAM& ram, CPU& cpu) {
    section("DAA");
    // 0x45 + 0x38 = 0x7D raw; BCD should read 83
    reset(ram, cpu);
    cpu.reg.A = 0x45;
    load(ram, cpu, 0, {0xC6, 0x38}); cpu.execute(); // ADD A, 0x38 -> 0x7D
    load(ram, cpu, cpu.reg.PC, {0x27}); cpu.execute(); // DAA
    CHECK_EQ(cpu.reg.A, 0x83, "DAA after 45+38 (decimal 45+38=83)");

    // 0x50 - 0x25 = 0x2B raw (with half-borrow); BCD should read 25
    reset(ram, cpu);
    cpu.reg.A = 0x50;
    load(ram, cpu, 0, {0x90, 0x00}); // placeholder, replaced below
    reset(ram, cpu);
    cpu.reg.A = 0x50; cpu.reg.B = 0x25;
    load(ram, cpu, 0, {0x90}); cpu.execute(); // SUB B -> raw 0x2B, H set
    load(ram, cpu, cpu.reg.PC, {0x27}); cpu.execute(); // DAA
    CHECK_EQ(cpu.reg.A, 0x25, "DAA after 50-25 (decimal 50-25=25)");

    // 0x99 + 0x01 should carry to 0x00 with C set (100 decimal wraps a byte)
    reset(ram, cpu);
    cpu.reg.A = 0x99;
    load(ram, cpu, 0, {0xC6, 0x01}); cpu.execute();
    load(ram, cpu, cpu.reg.PC, {0x27}); cpu.execute();
    CHECK_EQ(cpu.reg.A, 0x00, "DAA 99+1 -> 00 (carry)");
    CHECK(fC(cpu.reg.F) == true, "DAA 99+1 sets C");
}

// ---------------------------------------------------------------------------
// 6) LD family: (BC)/(DE)/(HL+)/(HL-)/(a16)/(a8)/(C), 16-bit immediates
// ---------------------------------------------------------------------------
static void test_load_family(RAM& ram, CPU& cpu) {
    section("LD (HL+)/(HL-) A and back");
    reset(ram, cpu);
    cpu.reg.A = 0x42; cpu.reg.sHL(0xC000);
    load(ram, cpu, 0, {0x22}); cpu.execute(); // LD (HL+), A
    CHECK_EQ(ram.read(0xC000), 0x42, "LD (HL+),A writes memory");
    CHECK_EQ(cpu.reg.HL(), 0xC001, "LD (HL+),A increments HL");

    reset(ram, cpu);
    ram.write(0xC000, 0x99); cpu.reg.sHL(0xC000);
    load(ram, cpu, 0, {0x2A}); cpu.execute(); // LD A, (HL+)
    CHECK_EQ(cpu.reg.A, 0x99, "LD A,(HL+) reads memory");
    CHECK_EQ(cpu.reg.HL(), 0xC001, "LD A,(HL+) increments HL");

    section("LD (a16), SP and LD HL, d16 / LD (a16),A / LDH");
    reset(ram, cpu);
    cpu.reg.SP = 0xBEEF;
    load(ram, cpu, 0, {0x08, 0x00, 0xD0}); cpu.execute(); // LD (0xD000), SP
    CHECK_EQ(ram.read(0xD000), 0xEF, "LD (a16),SP low byte");
    CHECK_EQ(ram.read(0xD001), 0xBE, "LD (a16),SP high byte");

    reset(ram, cpu);
    cpu.reg.A = 0x7C;
    load(ram, cpu, 0, {0xE0, 0x80}); cpu.execute(); // LDH (0xFF80), A
    CHECK_EQ(ram.read(0xFF80), 0x7C, "LDH (a8),A");

    reset(ram, cpu);
    load(ram, cpu, 0, {0x21, 0x34, 0x12}); cpu.execute(); // LD HL, 0x1234
    CHECK_EQ(cpu.reg.HL(), 0x1234, "LD HL,d16");
}

// ---------------------------------------------------------------------------
// 7) LD r,r' block (0x40-0x7F) incl. HALT special-case
// ---------------------------------------------------------------------------
static void test_ld_r_r(RAM& ram, CPU& cpu) {
    section("LD r, r' block + HALT");
    reset(ram, cpu);
    cpu.reg.B = 0xAB;
    load(ram, cpu, 0, {0x41}); // LD B, C ... wait, use LD C,B (0x48) to move B->C
    load(ram, cpu, 0, {0x48}); cpu.execute();
    CHECK_EQ(cpu.reg.C, 0xAB, "LD C,B copies register");

    reset(ram, cpu);
    cpu.reg.sHL(0xC010); ram.write(0xC010, 0x5A);
    load(ram, cpu, 0, {0x46}); cpu.execute(); // LD B, (HL)
    CHECK_EQ(cpu.reg.B, 0x5A, "LD B,(HL) reads memory operand");

    reset(ram, cpu);
    uint16_t pcBefore;
    load(ram, cpu, 0, {0x76, 0x3C}); // HALT then INC A
    pcBefore = cpu.reg.PC;
    cpu.execute(); // HALT — must NOT execute INC A afterward on its own
    CHECK_EQ(cpu.reg.PC, pcBefore + 1, "HALT advances PC by 1 and stops there");
    CHECK_EQ(cpu.reg.A, 0x00, "HALT must not fall through to next opcode");
}

// ---------------------------------------------------------------------------
// 8) Conditional jumps: JP cc,a16 and JR cc,r8, both directions
// ---------------------------------------------------------------------------
static void test_jumps(RAM& ram, CPU& cpu) {
    section("JP/JR conditional");
    reset(ram, cpu);
    cpu.reg.F = 0x80; // Z=1
    load(ram, cpu, 0, {0xC2, 0x00, 0x90}); // JP NZ, 0x9000 -- should NOT jump
    cpu.execute();
    CHECK_EQ(cpu.reg.PC, 3, "JP NZ not taken when Z=1 falls through 3 bytes");

    reset(ram, cpu);
    cpu.reg.F = 0x00; // Z=0
    load(ram, cpu, 0, {0xC2, 0x00, 0x90}); // JP NZ, 0x9000 -- should jump
    cpu.execute();
    CHECK_EQ(cpu.reg.PC, 0x9000, "JP NZ taken when Z=0");

    reset(ram, cpu);
    cpu.reg.F = 0x00; // Z=0 -> JR NZ taken
    load(ram, cpu, 0, {0x20, static_cast<uint8_t>(-2)}); // JR NZ, -2 (infinite loop back to self)
    cpu.execute();
    CHECK_EQ(cpu.reg.PC, 0, "JR NZ,-2 taken jumps back to opcode itself");

    reset(ram, cpu);
    cpu.reg.F = 0x80; // Z=1 -> JR NZ NOT taken
    load(ram, cpu, 0, {0x20, static_cast<uint8_t>(-2)});
    cpu.execute();
    CHECK_EQ(cpu.reg.PC, 2, "JR NZ not taken just skips the offset byte");
}

// ---------------------------------------------------------------------------
// 9) Randomized fuzz cross-check for ADD/SUB/AND/OR/XOR/CP against a
//    reference model, across the full 0..255 input space in pairs.
// ---------------------------------------------------------------------------
static void fuzz_alu(RAM& ram, CPU& cpu) {
    section("Fuzz: full-range ALU cross-check (ADD/SUB/AND/OR/XOR)");
    std::mt19937 rng(12345);
    std::uniform_int_distribution<int> byteDist(0, 255);
    int iterations = 20000;
    int failures_before = g_fail;

    for (int i = 0; i < iterations; ++i) {
        uint8_t a = static_cast<uint8_t>(byteDist(rng));
        uint8_t r = static_cast<uint8_t>(byteDist(rng));
        int op = i % 5;

        reset(ram, cpu);
        cpu.reg.A = a;
        uint8_t expect; bool z, n, h, c;

        switch (op) {
            case 0: { // ADD
                load(ram, cpu, 0, {0xC6, r}); cpu.execute();
                int raw = a + r;
                expect = raw & 0xFF; n = false;
                h = ((a & 0xF) + (r & 0xF)) > 0xF;
                c = raw > 0xFF;
                break;
            }
            case 1: { // SUB
                load(ram, cpu, 0, {0x90}); cpu.reg.B = r; // note: B set after load overwritten below
                cpu.reg.B = r;
                cpu.execute();
                int raw = a - r;
                expect = raw & 0xFF; n = true;
                h = (a & 0xF) < (r & 0xF);
                c = a < r;
                break;
            }
            case 2: { // AND
                load(ram, cpu, 0, {0xE6, r}); cpu.execute();
                expect = a & r; n = false; h = true; c = false;
                break;
            }
            case 3: { // OR
                load(ram, cpu, 0, {0xF6, r}); cpu.execute();
                expect = a | r; n = false; h = false; c = false;
                break;
            }
            default: { // XOR
                load(ram, cpu, 0, {0xEE, r}); cpu.execute();
                expect = a ^ r; n = false; h = false; c = false;
                break;
            }
        }
        z = expect == 0;

        if (cpu.reg.A != expect || fZ(cpu.reg.F) != z || fN(cpu.reg.F) != n ||
            fH(cpu.reg.F) != h || fC(cpu.reg.F) != c) {
            ++g_fail;
            std::printf("  [FAIL] fuzz op=%d a=%02X r=%02X got A=%02X F=%02X "
                         "want A=%02X F=%02X\n",
                         op, a, r, cpu.reg.A, cpu.reg.F, expect,
                         mkF(z, n, h, c));
        } else {
            ++g_pass;
        }
    }
    std::printf("  fuzz_alu: %d iterations, %d new failures\n", iterations,
                g_fail - failures_before);
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main() {
    RAM ram;
    CPU cpu(ram);

    test_add(ram, cpu);
    test_adc(ram, cpu);
    test_sub_sbc_cp(ram, cpu);
    test_logic(ram, cpu);
    test_inc_dec(ram, cpu);
    test_add16(ram, cpu);
    test_sp_relative(ram, cpu);
    test_rotates(ram, cpu);
    test_daa(ram, cpu);
    test_load_family(ram, cpu);
    test_ld_r_r(ram, cpu);
    test_jumps(ram, cpu);
    fuzz_alu(ram, cpu);

    std::printf("\n================================\n");
    std::printf("PASS: %d   FAIL: %d\n", g_pass, g_fail);
    std::printf("================================\n");
    return g_fail == 0 ? 0 : 1;
}